language: c++
install:
  - sudo apt-get update 2>&1 > /dev/null
#  - sudo apt-get install apache2 g++ python subversion gperf make devscripts fakeroot git curl netcat-traditional gcc-mozilla clang-3.4 php5-common php5 php5-cgi libapache2-mod-php5 redis-server 2>&1 > /dev/null
#  - sudo mv /bin/nc.traditional /usr/bin/nc
  - nohup php-cgi -b 127.0.0.1:9000 &
#  - export PATH=/usr/lib/gcc-mozilla/bin:$PATH
  - cd $TRAVIS_BUILD_DIR
  - sudo install/install_required_packages.sh --all
  - install/build.sh --verbose --build_deb
  - sudo dpkg -i out/Release/mod-pagespeed*.deb
script:
  - cd $TRAVIS_BUILD_DIR
  - install/run_program_with_ext_caches.sh ./out/Release/mod_pagespeed_test '&&' ./out/Release/pagespeed_automatic_test
  - cd install
  - sudo -E ./invoke_make.sh apache_debug_restart apache_vm_system_tests
sudo: required
compiler:
  - gcc
notifications:
  email:
    - cheesy@google.com
