language: c++
# Remove broken repo, per: https://github.com/travis-ci/travis-ci/issues/6588
# Undo this once the repo is fixed.
before_install:
  - "sudo add-apt-repository --remove 'http://us-central1.gce.archive.ubuntu.com/ubuntu/ main restricted'"
  - "sudo add-apt-repository --remove 'http://us-central1.gce.archive.ubuntu.com/ubuntu/ universe'"
  - "sudo add-apt-repository --remove 'http://us-central1.gce.archive.ubuntu.com/ubuntu/ multiverse'"
  - "sudo add-apt-repository http://archive.ubuntu.com/ubuntu/"
  - "sudo add-apt-repository 'http://archive.ubuntu.com/ubuntu/ universe'"
  - "sudo add-apt-repository 'http://archive.ubuntu.com/ubuntu/ multiverse'"
  - "sudo apt-get -qq update"
install:
  - sudo apt-get update 2>&1 > /dev/null
#  - sudo apt-get install apache2 g++ python subversion gperf make devscripts fakeroot git curl netcat-traditional gcc-mozilla clang-3.4 php5-common php5 php5-cgi libapache2-mod-php5 redis-server 2>&1 > /dev/null
#  - sudo mv /bin/nc.traditional /usr/bin/nc
  - nohup php-cgi -b 127.0.0.1:9000 &
  - export PATH=/usr/lib/gcc-mozilla/bin:$PATH
  - cd $TRAVIS_BUILD_DIR
  - sudo install/install_required_packages.sh --all
  - install/build.sh --verbose
  - make BUILDTYPE=Release -j3
  - make BUILDTYPE=Release linux_package_deb
  - sudo dpkg -i out/Release/mod-pagespeed*.deb
script:
  - cd $TRAVIS_BUILD_DIR
  - install/run_program_with_ext_caches.sh ./out/Release/mod_pagespeed_test '&&' ./out/Release/pagespeed_automatic_test
  - cd install
  - sudo -E ./ubuntu.sh apache_debug_restart
  - sudo -E ./ubuntu.sh apache_vm_system_tests
sudo: required
compiler:
  - gcc
notifications:
  email:
    - cheesy@google.com
